request processing
MlynorikAlina/file_processing pull request #1
Opened 2020-10-07 18:31 UTC by MlynorikAlina

2020-10-07 19:05 UTC, VeronikaYastr requested changes

2020-10-07 19:05 UTC, VeronikaYastr commented on src/main/com/bsu/Company.java
> +        name = args[0];
Здесь желательно добавить проверку, что элементов в массиве нужное количество

2020-10-07 19:05 UTC, VeronikaYastr commented on src/main/com/bsu/Company.java
> +    Company(String[] args) throws ParseException {
Конструктор лучше сделать публичным

2020-10-07 19:05 UTC, VeronikaYastr commented on src/main/com/bsu/Company.java
> +    @Override
Обычно еще переопределяют equals, hashCode методы

2020-10-07 19:05 UTC, VeronikaYastr commented on src/main/com/bsu/Company.java
> +        String[] lineArgs;
Лучше это считывание перенести в main все таки

2020-10-07 19:05 UTC, VeronikaYastr commented on src/main/com/bsu/Main.java
> +            try (Scanner inputFile = new Scanner(new FileReader(inputFileName));
Можно это в том же try, что и в начале

2020-10-07 19:05 UTC, VeronikaYastr commented on src/main/com/bsu/Query.java
> +        companyList.forEach(company -> {
Лучше сделать companyList.stream().filter(c -> /condition/).collect(Collectors.toList())
Аналогично в след запросах

2020-10-07 19:05 UTC, VeronikaYastr commented on src/main/com/bsu/Query.java
> +    static List<Company> findByFoundationDate(List<Company> companyList, Date date1, Date date2) {
Лучше назвать startDate, endDate, например.

2020-10-07 19:05 UTC, VeronikaYastr commented on src/main/com/bsu/Query.java
> +    static void getInfoByRequest(Scanner scanner, List<Company> companyList) throws ParseException {
Этот метод лучше в мэйн вынести

2020-10-07 19:05 UTC, VeronikaYastr commented on src/main/com/bsu/Query.java
> +                    System.out.println("Enter 2 numbers(from .. to):");
можно здесь еще добавить try-catch и выше там, где парсинг. Чтобы выводилось сообщение о неверном формате и было понятно, откуда оно.

2020-10-08 06:52 UTC, MlynorikAlina commented on src/main/com/bsu/Company.java
> +    @Override
добавила

2020-10-08 06:53 UTC, MlynorikAlina commented on src/main/com/bsu/Company.java
> +        String[] lineArgs;
Done

2020-10-08 07:01 UTC, MlynorikAlina commented on src/main/com/bsu/Company.java
> +    Company(String[] args) throws ParseException {
Done

2020-10-08 07:39 UTC, MlynorikAlina commented on src/main/com/bsu/Company.java
> +        name = args[0];
Done

2020-10-08 07:40 UTC, MlynorikAlina commented on src/main/com/bsu/Main.java
> +            try (Scanner inputFile = new Scanner(new FileReader(inputFileName));
Done

2020-10-08 16:05 UTC, MlynorikAlina commented on src/main/com/bsu/Query.java
> +        companyList.forEach(company -> {
Сделала

2020-10-08 16:09 UTC, MlynorikAlina commented on src/main/com/bsu/Query.java
> +    static void getInfoByRequest(Scanner scanner, List<Company> companyList) throws ParseException {
вынесла

2020-10-08 16:50 UTC, MlynorikAlina commented on src/main/com/bsu/Query.java
> +                    System.out.println("Enter 2 numbers(from .. to):");
done

2020-10-27 16:22 UTC, merged